### ISSUE TITLE
numpy.core.multiarray failed to import while importing ADflow

### ISSUE THREAD

**Issue by joanibal** [mdolab/adflow#177]
I'm documenting this so others can search it.

I had the following error when trying to import.

`
Traceback (most recent call last):
  File "/home/josh/repos/adflow/adflow/pyADflow.py", line 88, in __init__
    self.adflow
AttributeError: 'ADFLOW' object has no attribute 'adflow'

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
EException ignored in: <function MExt.__del__ at 0x7fa8c80c5940>
Traceback (most recent call last):
  File "/home/josh/repos/adflow/adflow/MExt.py", line 60, in __del__
    del sys.modules[self._module.__name__]
AttributeError: 'MExt' object has no attribute '_module'

======================================================================
ERROR: test_solve (__main__.LowSpeedTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/josh/repos/adflow/adflow/pyADflow.py", line 88, in __init__
    self.adflow
AttributeError: 'ADFLOW' object has no attribute 'adflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_lowspeed_precon.py", line 54, in setUp
    self.CFDSolver = ADFLOW(options=self.aero_options)
  File "/home/josh/repos/adflow/adflow/pyADflow.py", line 91, in __init__
    self.adflow = MExt.MExt("libadflow", curDir, debug=debug)._module
  File "/home/josh/repos/adflow/adflow/MExt.py", line 49, in __init__
    self._pkg = __import__(self._pkgname, globals(), locals(), [self.name])
ImportError: numpy.core.multiarray failed to import
`

**Comment by joanibal** [comment]
I had compiled the code with a different version of numpy.
The fix is simply to compile and run with the same version.
