### ISSUE TITLE
libadflow.error: try_pyarr_from_string failed

### ISSUE THREAD

**Issue by Zcaic** [mdolab/adflow#217]
### Steps to reproduce issue

1. …when I run command "mpirun -n 1 python aero_run.py" as I follow tutorial
2. …it gets a error:
libadflow.error is related to 
Traceback (most recent call last):
  File "aero_run.py", line 42, in <module>
    CFDSolver = ADFLOW(options=aeroOptions)
  File "/usr/Python38_venv/lib/python3.8/site-packages/adflow/pyADflow.py", line 147, in __init__
    super().__init__(
  File "/usr/Python38_venv/lib/python3.8/site-packages/baseclasses/solvers/pyAero_solver.py", line 45, in __init__
    super().__init__(
  File "/usr/Python38_venv/lib/python3.8/site-packages/baseclasses/solvers/BaseSolver.py", line 86, in __init__
    self.setOption(key, optionValue)
  File "/usr/Python38_venv/lib/python3.8/site-packages/adflow/pyADflow.py", line 4704, in setOption
    self.adflow.inputparamroutines.isovariables(varStr)
libadflow.error: try_pyarr_from_string failed

anyone knows how to solve it?
thanks!

### Code versions

- Operating System: unbuntu 20.04
- Python: python3.8
- OpenMPI: Open MPI 4.0.3
- CGNS: CGNS-4.1.2
- PETSc: petsc-3.17.1
- Compiler:
- This repository:

**Comment by nwu63** [comment]
What's your numpy version? My best guess is that you're using a version of numpy that's too recent and probably contains a bug or something (in f2py). Also, your PETSc version is quite new as well. The versions of dependencies we test/support can be found [here](https://mdolab-mach-aero.readthedocs-hosted.com/en/latest/installInstructions/install3rdPartyPackages.html#supported-dependency-versions).

**Comment by nwu63** [comment]
Closing due to inactivity.
