### ISSUE TITLE
ADflow doesn't work with numpy 1.24

### ISSUE THREAD

**Issue by A-CGray** [mdolab/adflow#256]
## Description

Self explanatory. We are trying to update the "latest" docker images to numpy 1.24 (https://github.com/mdolab/docker/pull/208) and getting the error below in all the ADflow tests when calling `setattr`, my best guess is that something changed in f2py.

### Steps to reproduce issue

1. Install numpy v1.24
2. Run ADflow tests

### Current behavior
```text
 (mpi) /home/***/repos/adflow/tests/unit_tests/test_restart.py:BasicTests.test_import_block_splitting ... FAIL (00:00:0.03, 159 MB)
Traceback (most recent call last):
  File "/home/***/.pyenv/versions/3.10.9/lib/python3.10/site-packages/testflo/test.py", line 418, in _try_call
    func()
  File "/home/***/repos/adflow/tests/unit_tests/test_restart.py", line 33, in test_import_block_splitting
    CFDSolver = ADFLOW(options=self.options, debug=False)
  File "/home/***/.pyenv/versions/3.10.9/lib/python3.10/site-packages/adflow/pyADflow.py", line 148, in __init__
    super().__init__(
  File "/home/***/.pyenv/versions/3.10.9/lib/python3.10/site-packages/baseclasses/solvers/pyAero_solver.py", line 45, in __init__
    super().__init__(
  File "/home/***/.pyenv/versions/3.10.9/lib/python3.10/site-packages/baseclasses/solvers/BaseSolver.py", line 86, in __init__
    self.setOption(key, optionValue)
  File "/home/***/.pyenv/versions/3.10.9/lib/python3.10/site-packages/adflow/pyADflow.py", line 5207, in setOption
    setattr(module, variable, value)
ValueError: 0-th dimension must be 256 but got 0 (not defined).
```

### Expected behavior
All tests pass

**Comment by sseraj** [comment]
The errors in the issue description are caused by a bug in f2py that has recently been fixed in https://github.com/numpy/numpy/pull/23194. I built numpy with the fix from source (`1.25.0.dev0+678.g51ecf8401`), recompiled ADflow, and all the tests passed. We just need to wait for the next patch release, which should include this fix. The same applies to pyHyp.

There is a separate bug that occurs in ADflow when updating from 1.21 to 1.22. This looks like the intended behavior from f2py related to `intent(out)` strings of undetermined length:

```
File "/home/mdolabuser/repos/adflow/adflow/pyADflow.py", line 5065, in setOption
    self.adflow.inputparamroutines.isovariables(varStr)
libadflow.error: try_pyarr_from_string failed
```

This bug is relatively easy to fix in ADflow, so I will open a PR to address that.

**Comment by A-CGray** [comment]
> The errors in the issue description are caused by a bug in f2py that has recently been fixed in [numpy/numpy#23194](https://github.com/numpy/numpy/pull/23194). I built numpy with the fix from source (`1.25.0.dev0+678.g51ecf8401`), recompiled ADflow, and all the tests passed. We just need to wait for the next patch release, which should include this fix. The same applies to pyHyp.
> 
> There is a separate bug that occurs in ADflow when updating from 1.21 to 1.22. This looks like the intended behavior from f2py related to `intent(out)` strings of undetermined length:
> 
> ```
> File "/home/mdolabuser/repos/adflow/adflow/pyADflow.py", line 5065, in setOption
>     self.adflow.inputparamroutines.isovariables(varStr)
> libadflow.error: try_pyarr_from_string failed
> ```
> 
> This bug is relatively easy to fix in ADflow, so I will open a PR to address that.

Awesome, nice work!

**Comment by A-CGray** [comment]
I think when numpy 1.24.3 is released we should update the requirements in `setup.py` to reflect the versions of numpy that does work with. We can close this issue with that PR.
