### ISSUE TITLE
ADFlow verification

### ISSUE THREAD

**Issue by bustinov** [mdolab/adflow#282]
Try to run test to check ADFlow: testflo . 
but get error: 

(mpi) ./tests/reg_tests/test_time_spectral_naca64A010.py:TestSolve.test_solve  ... FAIL (00:00:0.03, 163 MB)
Traceback (most recent call last):
  File "/home/user/packages/adflow-2.8.0/./tests/reg_tests/test_time_spectral_naca64A010.py", line 140, in setUp
    self.CFDSolver = ADFLOW(options=options, debug=False)
  File "/home/user/.local/lib/python3.10/site-packages/adflow/pyADflow.py", line 147, in __init__
    super().__init__(
  File "/home/user/.local/lib/python3.10/site-packages/baseclasses/solvers/pyAero_solver.py", line 45, in __init__
    super().__init__(
  File "/home/user/.local/lib/python3.10/site-packages/baseclasses/solvers/BaseSolver.py", line 86, in __init__
    self.setOption(key, optionValue)
  File "/home/user/.local/lib/python3.10/site-packages/adflow/pyADflow.py", line 5046, in setOption
    self.adflow.inputparamroutines.isovariables(varStr)
libadflow.error: try_pyarr_from_string failed

If I use NumPy 1.21, get:
module compiled against API version 0x10 but this version of numpy is 0xe

- Operating System: Ubuntu 22.04
- Python: 3.10
- OpenMPI: 4.1.5
- CGNS: 4.3.0
- PETSc: 3.19
- NumPy: 1.24.3
- Compiler: gfortran
- This repository: 2.8.0

**Comment by bustinov** [comment]
https://github.com/mdolab/adflow/pull/262
this work for me

**Comment by sseraj** [comment]
Closing because this looks resolved
